services:
  db:
    image: postgres:latest
    ports:
      - 5438:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${CM_PASSWORD}
      - POSTGRES_USER=${CM_USER}
      - POSTGRES_DB=${CM_DB_NAME}

volumes:
  postgres: