spring:
  datasource:
    url: ${CM_DB_URL}
    username: ${CM_USER}
    password: ${CM_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
           auth: true
           starttls:
             enable: true
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 86400000
  refresh-token-expiration: 0




